name: Build e Deploy para o GCR e o Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest -f frontend/Dockerfile frontend
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest -f backend/Dockerfile backend

    - name: Push Docker images to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated
        gcloud run deploy backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
