name: Build and Deploy to GCR and Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest -f frontend/Dockerfile frontend
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest -f backend/Dockerfile backend

    - name: Push Docker images to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
        gcloud run deploy backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
