name: Build and Deploy to Artifact Registry and Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA }}

    - name: Configure Docker to use Google Artifact Registry
      run: |
        gcloud auth configure-docker us-east1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/frontend:latest -f frontend/Dockerfile frontend
        docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/backend:latest -f backend/Dockerfile backend

    - name: Push Docker images to Artifact Registry
      run: |
        docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/frontend:latest
        docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/backend:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy frontend \
          --image us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/frontend:latest \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated
        gcloud run deploy backend \
          --image us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/backend:latest \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated
